// Bake-build reads .env from the module root, generates a short-lived Go file that sets
// bakedNetlifyToken / bakedNetlifySiteID in init(), runs go build, then deletes the
// generated file (unless -keep). Use this instead of hand-written -ldflags -X.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"web_editor/internal/envload"
)

const genFileName = "z_baked_env.gen.go"

const genPreamble = `// Code generated by bake-build; DO NOT EDIT.

package main

func init() {
`

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from current directory")
		}
		dir = parent
	}
}

func writeGen(root, token, siteID string) (string, error) {
	path := filepath.Join(root, "cmd/projectwhy", genFileName)
	var b strings.Builder
	b.WriteString(genPreamble)
	fmt.Fprintf(&b, "\tbakedNetlifyToken = %s\n", strconv.Quote(token))
	fmt.Fprintf(&b, "\tbakedNetlifySiteID = %s\n", strconv.Quote(siteID))
	b.WriteString("}\n")
	err := os.WriteFile(path, []byte(b.String()), 0o600)
	return path, err
}

func removeGen(path string) {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		log.Printf("remove %s: %v", path, err)
	}
}

func main() {
	envPath := flag.String("env", ".env", "path to .env (relative to module root)")
	out := flag.String("o", filepath.Join("dist", "projectwhy"), "output binary path (relative to module root unless absolute)")
	extraLdflags := flag.String("ldflags", "", "extra -ldflags content (e.g. -X main.version=1.0.0), appended after -s -w")
	keep := flag.Bool("keep", false, "keep the generated z_baked_env.gen.go file after build")
	flag.Parse()

	root, err := findModuleRoot()
	if err != nil {
		log.Fatal(err)
	}

	genPath := filepath.Join(root, "cmd/projectwhy", genFileName)
	envAbs := *envPath
	if !filepath.IsAbs(envAbs) {
		envAbs = filepath.Join(root, envAbs)
	}

	var token, siteID string
	m, err := envload.ParseFile(envAbs)
	if err != nil {
		if os.IsNotExist(err) {
			removeGen(genPath)
		} else {
			log.Fatal(err)
		}
	} else {
		token = strings.TrimSpace(m["PROJECTWHY_NETLIFY_TOKEN"])
		siteID = strings.TrimSpace(m["PROJECTWHY_NETLIFY_SITE_ID"])
	}

	baked := token != "" || siteID != ""
	if baked {
		if _, err := writeGen(root, token, siteID); err != nil {
			log.Fatal(err)
		}
		fmt.Println("bake-build: baked PROJECTWHY_NETLIFY_TOKEN / PROJECTWHY_NETLIFY_SITE_ID from", envAbs)
	} else {
		removeGen(genPath)
		fmt.Println("bake-build: no Netlify keys in .env; building without baked defaults")
	}

	if !*keep {
		defer removeGen(genPath)
	}

	outPath := *out
	if !filepath.IsAbs(outPath) {
		outPath = filepath.Join(root, outPath)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		log.Fatal(err)
	}

	ldflags := "-s -w"
	if x := strings.TrimSpace(*extraLdflags); x != "" {
		ldflags += " " + x
	}

	args := []string{"build", "-ldflags", ldflags, "-o", outPath, "./cmd/projectwhy"}
	cmd := exec.Command("go", args...)
	cmd.Dir = root
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = os.Environ()
	if err := cmd.Run(); err != nil {
		if !*keep {
			removeGen(genPath)
		}
		log.Fatal(err)
	}
	fmt.Println("bake-build:", outPath)
}
