// Bake-build reads a per-site .env, generates a short-lived Go file that sets
// bakedNetlifyToken / bakedNetlifySiteID, optional Cloudflare baked vars,
// bakedDeployProvider (from PROJECTWHY_DEFAULT_DEPLOY_PROVIDER), and optional
// bakedProjectFolder (from PROJECTWHY_PROJECT_FOLDER) in init(),
// runs go build, then deletes the generated file (unless -keep). Use this instead of hand-written -ldflags -X.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	"web_editor/internal/envload"
	"web_editor/internal/version"
)

const genFileName = "z_baked_env.gen.go"

const genPreamble = `// Code generated by bake-build; DO NOT EDIT.

package main

func init() {
`

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from current directory")
		}
		dir = parent
	}
}

func writeGen(root, token, siteID, cfTok, cfAcct, cfProj, deployProvider, projectFolder string) (string, error) {
	path := filepath.Join(root, "cmd/projectwhy", genFileName)
	var b strings.Builder
	b.WriteString(genPreamble)
	fmt.Fprintf(&b, "\tbakedNetlifyToken = %s\n", strconv.Quote(token))
	fmt.Fprintf(&b, "\tbakedNetlifySiteID = %s\n", strconv.Quote(siteID))
	fmt.Fprintf(&b, "\tbakedCfApiToken = %s\n", strconv.Quote(cfTok))
	fmt.Fprintf(&b, "\tbakedCfAccountID = %s\n", strconv.Quote(cfAcct))
	fmt.Fprintf(&b, "\tbakedCfProjectName = %s\n", strconv.Quote(cfProj))
	fmt.Fprintf(&b, "\tbakedDeployProvider = %s\n", strconv.Quote(deployProvider))
	fmt.Fprintf(&b, "\tbakedProjectFolder = %s\n", strconv.Quote(projectFolder))
	b.WriteString("}\n")
	err := os.WriteFile(path, []byte(b.String()), 0o600)
	return path, err
}

func removeGen(path string) {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		log.Printf("remove %s: %v", path, err)
	}
}

// envForGoBuild returns a copy of the environment with GOOS/GOARCH/CGO_ENABLED set for the
// nested `go build` only. Use this instead of exporting GOOS=… when running `go run ./cmd/bake-build`:
// that would compile bake-build itself for the target OS and fail with exec format error on Linux/macOS.
func envForGoBuild(goos, goarch string) []string {
	var out []string
	for _, e := range os.Environ() {
		ue := strings.ToUpper(e)
		if strings.HasPrefix(ue, "GOOS=") || strings.HasPrefix(ue, "GOARCH=") || strings.HasPrefix(ue, "CGO_ENABLED=") {
			continue
		}
		out = append(out, e)
	}
	out = append(out, "GOOS="+goos, "GOARCH="+goarch)
	if goos != runtime.GOOS || goarch != runtime.GOARCH {
		out = append(out, "CGO_ENABLED=0")
	}
	return out
}

func main() {
	envPath := flag.String("env", ".env", "path to .env (relative to module root)")
	out := flag.String("o", "", "output binary path (default: dist/projectwhy_<version>[.exe] on windows)")
	goos := flag.String("goos", runtime.GOOS, "GOOS for the built binary (e.g. windows when cross-compiling from Linux)")
	goarch := flag.String("goarch", runtime.GOARCH, "GOARCH for the built binary (e.g. amd64)")
	extraLdflags := flag.String("ldflags", "", "extra -ldflags content, appended after -s -w and -X main.version")
	keep := flag.Bool("keep", false, "keep the generated z_baked_env.gen.go file after build")
	flag.Parse()

	root, err := findModuleRoot()
	if err != nil {
		log.Fatal(err)
	}

	genPath := filepath.Join(root, "cmd/projectwhy", genFileName)
	envAbs := *envPath
	if !filepath.IsAbs(envAbs) {
		envAbs = filepath.Join(root, envAbs)
	}

	var token, siteID, cfTok, cfAcct, cfProj, deployProvider, projectFolder string
	m, err := envload.ParseFile(envAbs)
	if err != nil {
		if os.IsNotExist(err) {
			removeGen(genPath)
		} else {
			log.Fatal(err)
		}
	} else {
		token = strings.TrimSpace(m["PROJECTWHY_NETLIFY_TOKEN"])
		siteID = strings.TrimSpace(m["PROJECTWHY_NETLIFY_SITE_ID"])
		cfTok = strings.TrimSpace(m["PROJECTWHY_CF_API_TOKEN"])
		cfAcct = strings.TrimSpace(m["PROJECTWHY_CF_ACCOUNT_ID"])
		cfProj = strings.TrimSpace(m["PROJECTWHY_CF_PROJECT_NAME"])
		deployProvider = strings.TrimSpace(m["PROJECTWHY_DEFAULT_DEPLOY_PROVIDER"])
		projectFolder = strings.TrimSpace(m["PROJECTWHY_PROJECT_FOLDER"])
		if projectFolder != "" {
			if clean := filepath.Base(projectFolder); clean != projectFolder || clean == "." || clean == ".." {
				log.Fatalf("PROJECTWHY_PROJECT_FOLDER must be a single folder name under the user home (got %q)", projectFolder)
			}
		}
	}

	baked := token != "" || siteID != "" || cfTok != "" || cfAcct != "" || cfProj != "" || deployProvider != "" || projectFolder != ""
	if baked {
		if _, err := writeGen(root, token, siteID, cfTok, cfAcct, cfProj, deployProvider, projectFolder); err != nil {
			log.Fatal(err)
		}
		fmt.Println("bake-build: baked deploy defaults from", envAbs)
	} else {
		removeGen(genPath)
		fmt.Println("bake-build: no deploy keys in .env; building without baked defaults")
	}

	if !*keep {
		defer removeGen(genPath)
	}

	outPath := strings.TrimSpace(*out)
	if outPath == "" {
		base := "projectwhy_" + version.Version
		if *goos == "windows" {
			base += ".exe"
		}
		outPath = filepath.Join("dist", base)
	}
	if !filepath.IsAbs(outPath) {
		outPath = filepath.Join(root, outPath)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		log.Fatal(err)
	}

	ldflags := "-s -w -X main.version=" + version.Version
	if x := strings.TrimSpace(*extraLdflags); x != "" {
		ldflags += " " + x
	}

	args := []string{"build", "-ldflags", ldflags, "-o", outPath, "./cmd/projectwhy"}
	cmd := exec.Command("go", args...)
	cmd.Dir = root
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = envForGoBuild(*goos, *goarch)
	if err := cmd.Run(); err != nil {
		if !*keep {
			removeGen(genPath)
		}
		log.Fatal(err)
	}
	fmt.Println("bake-build:", outPath)
}
